

name: CI

on:
  push:
    branches: [ master ]

env:
  BUCKET: polpasnatural.com.br

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test --watchAll false
    
    - name: Build
      run: yarn build
       
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Upload field to bucket
      run: gsutil -m rsync -R ./build gs://"SOCKET"
    
    
    - name: Allow AllUsers
      run: gsutil -m acl ch -R -u AllUsers:R gs://"SOCKET"
    
    - name: Set Cache-control
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"SOCKET"/**/*.{svg,js}
    
    - name: Set Cache-control
      run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://"SOCKET"/index.html
